export const REDUX_FIELD_NAME = 'fields';

export const SIMPLE_REDUX_FIELD__OPEN = 'SIMPLE_REDUX_FIELD__OPEN';
export const SIMPLE_REDUX_FIELD__CLOSE = 'SIMPLE_REDUX_FIELD__CLOSE';
export const SIMPLE_REDUX_FIELD__OPEN_MULTIPLE = 'SIMPLE_REDUX_FIELD__OPEN_MULTIPLE';
export const SIMPLE_REDUX_FIELD__CLOSE_MULTIPLE = 'SIMPLE_REDUX_FIELD__CLOSE_MULTIPLE';
